# SPDX-License-Identifier: MIT
"""Port of upstream ``DocumentationSamplesForGitFlow.cs`` (6.8.2), non-Mainline cases.

Each test follows the documented walkthrough step by step; the Mainline
variants land with Phase 4.
"""

from __future__ import annotations

import pytest

from tests.scenarios.dsl import Scenario, gitflow

pytestmark = pytest.mark.scenario


def _finish_into(f: Scenario, target: str, branch: str, pr_version: str, with_pr: bool) -> None:
    """The shared "merge via optional pull request, then delete" tail of each sample."""
    f.checkout(target)
    if with_pr:
        f.branch_to("pull/2/merge")
        f.merge_no_ff(branch)
        f.assert_full_semver(pr_version, gitflow())
        f.checkout(target)
        f.delete_branch("pull/2/merge")
    f.merge_no_ff(branch)
    f.delete_branch(branch)


@pytest.mark.parametrize("with_pr", [False, True])
def test_feature_from_main_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("feature/foo")
        f.assert_full_semver("1.2.1-foo.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("1.2.1-foo.1+1", c)
        f.checkout("main")
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.apply_tag("1.2.1")
        f.assert_full_semver("1.2.1", c)
        f.merge_to("feature/foo")
        f.assert_full_semver("1.2.2-foo.1+2", c)
        f.make_a_commit("+semver: minor")
        f.assert_full_semver("1.3.0-foo.1+3", c)
        f.apply_tag("2.0.0-foo.1")
        f.assert_full_semver("2.0.0-foo.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.0-foo.2+1", c)
        _finish_into(f, "main", "feature/foo", "2.0.0-PullRequest2.5", with_pr)
        f.assert_full_semver("2.0.0-5", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.0-6", c)
        f.apply_tag("2.0.0")
        f.assert_full_semver("2.0.0", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_feature_from_develop_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("develop")
        f.assert_full_semver("1.3.0-alpha.0", c)
        f.branch_to("feature/foo")
        f.assert_full_semver("1.3.0-foo.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("1.3.0-foo.1+1", c)
        f.checkout("main")
        f.make_a_commit("+semver: minor")
        f.assert_full_semver("1.3.0-1", c)
        f.apply_tag("1.3.0")
        f.assert_full_semver("1.3.0", c)
        f.merge_to("develop")
        f.assert_full_semver("1.4.0-alpha.1", c)
        f.merge_to("feature/foo")
        f.assert_full_semver("1.4.0-foo.1+3", c)
        f.make_a_commit("+semver: major")
        f.assert_full_semver("2.0.0-foo.1+4", c)
        f.apply_tag("2.1.0-foo.1")
        f.assert_full_semver("2.1.0-foo.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.1.0-foo.2+1", c)
        _finish_into(f, "develop", "feature/foo", "2.1.0-PullRequest2.6", with_pr)
        f.assert_full_semver("2.1.0-alpha.6", c)
        f.make_a_commit()
        f.assert_full_semver("2.1.0-alpha.7", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_hotfix_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("hotfix/next")
        f.assert_full_semver("1.2.1-beta.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("1.2.1-beta.1+1", c)
        f.checkout("main")
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.apply_tag("1.2.1")
        f.assert_full_semver("1.2.1", c)
        f.merge_to("hotfix/next")
        f.assert_full_semver("1.2.2-beta.1+2", c)
        f.make_a_commit("+semver: minor")
        f.assert_full_semver("1.3.0-beta.1+3", c)
        f.apply_tag("2.0.0-beta.1")
        f.assert_full_semver("2.0.0-beta.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.0-beta.2+1", c)
        _finish_into(f, "main", "hotfix/next", "2.0.0-PullRequest2.5", with_pr)
        f.assert_full_semver("2.0.0-5", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.0-6", c)
        f.apply_tag("2.0.0")
        f.assert_full_semver("2.0.0", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_versioned_hotfix_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("hotfix/2.2.1")
        f.assert_full_semver("2.2.1-beta.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.2.1-beta.1+1", c)
        f.checkout("main")
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.apply_tag("2.2.1")
        f.assert_full_semver("2.2.1", c)
        f.merge_to("hotfix/2.2.1")
        f.assert_full_semver("2.2.2-beta.1+2", c)
        f.make_a_commit("+semver: major")
        f.assert_full_semver("3.0.0-beta.1+3", c)
        f.apply_tag("3.0.1-beta.1")
        f.assert_full_semver("3.0.1-beta.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("3.0.1-beta.2+1", c)
        _finish_into(f, "main", "hotfix/2.2.1", "3.0.1-PullRequest2.5", with_pr)
        f.assert_full_semver("3.0.1-5", c)
        f.make_a_commit()
        f.assert_full_semver("3.0.1-6", c)
        f.apply_tag("3.0.1")
        f.assert_full_semver("3.0.1", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_release_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("release/next")
        f.assert_full_semver("1.3.0-beta.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("1.3.0-beta.1+1", c)
        f.checkout("main")
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.apply_tag("1.2.1")
        f.assert_full_semver("1.2.1", c)
        f.merge_to("release/next")
        f.assert_full_semver("1.3.0-beta.1+2", c)
        f.make_a_commit("+semver: major")
        f.assert_full_semver("2.0.0-beta.1+3", c)
        f.apply_tag("2.0.1-beta.1")
        f.assert_full_semver("2.0.1-beta.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.1-beta.2+1", c)
        _finish_into(f, "main", "release/next", "2.0.1-PullRequest2.5", with_pr)
        f.assert_full_semver("2.0.1-5", c)
        f.make_a_commit()
        f.assert_full_semver("2.0.1-6", c)
        f.apply_tag("2.0.1")
        f.assert_full_semver("2.0.1", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_versioned_release_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("release/2.2.1")
        f.assert_full_semver("2.2.1-beta.1+0", c)
        f.make_a_commit()
        f.assert_full_semver("2.2.1-beta.1+1", c)
        f.checkout("main")
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.apply_tag("2.2.1")
        f.assert_full_semver("2.2.1", c)
        f.merge_to("release/2.2.1")
        f.assert_full_semver("2.3.0-beta.1+2", c)
        f.make_a_commit("+semver: major")
        f.assert_full_semver("3.0.0-beta.1+3", c)
        f.apply_tag("3.0.1-beta.1")
        f.assert_full_semver("3.0.1-beta.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("3.0.1-beta.2+1", c)
        _finish_into(f, "main", "release/2.2.1", "3.0.1-PullRequest2.5", with_pr)
        f.assert_full_semver("3.0.1-5", c)
        f.make_a_commit()
        f.assert_full_semver("3.0.1-6", c)
        f.apply_tag("3.0.1")
        f.assert_full_semver("3.0.1", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_develop_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("develop")
        f.assert_full_semver("1.3.0-alpha.0", c)
        f.make_a_commit()
        f.assert_full_semver("1.3.0-alpha.1", c)
        f.branch_to("release/1.3.0")
        f.assert_full_semver("1.3.0-beta.1+1", c)
        f.make_a_commit()
        f.assert_full_semver("1.3.0-beta.1+2", c)
        f.checkout("develop")
        f.assert_full_semver("1.4.0-alpha.0", c)
        f.merge_no_ff("release/1.3.0")
        f.assert_full_semver("1.4.0-alpha.2", c)
        f.checkout("main")
        f.merge_no_ff("release/1.3.0")
        f.delete_branch("release/1.3.0")
        f.apply_tag("1.3.0")
        f.assert_full_semver("1.3.0", c)
        f.make_a_commit()
        f.assert_full_semver("1.3.1-1", c)
        f.apply_tag("1.3.1")
        f.assert_full_semver("1.3.1", c)
        f.merge_to("develop")
        f.assert_full_semver("1.4.0-alpha.2", c)
        f.make_a_commit("+semver: major")
        f.assert_full_semver("2.0.0-alpha.3", c)
        f.apply_tag("2.1.0-alpha.1")
        f.assert_full_semver("2.1.0-alpha.1", c)
        f.make_a_commit()
        f.assert_full_semver("2.1.0-alpha.2", c)
        f.checkout("main")
        if with_pr:
            f.branch_to("pull/2/merge")
            f.merge_no_ff("develop")
            f.assert_full_semver("2.1.0-PullRequest2.5", c)
            f.checkout("main")
            f.delete_branch("pull/2/merge")
        f.merge_no_ff("develop")
        f.assert_full_semver("2.1.0-5", c)
        f.make_a_commit()
        f.assert_full_semver("2.1.0-6", c)
        f.apply_tag("2.1.0")
        f.assert_full_semver("2.1.0", c)


@pytest.mark.parametrize("with_pr", [False, True])
def test_support_branch(with_pr: bool) -> None:
    c = gitflow()
    with Scenario() as f:
        f.make_a_commit()
        f.apply_tag("1.2.0")
        f.assert_full_semver("1.2.0", c)
        f.branch_to("support/1.x")
        f.assert_full_semver("1.2.0", c)
        f.make_a_commit()
        f.assert_full_semver("1.2.1-1", c)
        f.checkout("main")
        f.make_a_commit("+semver: major")
        f.assert_full_semver("2.0.0-1", c)
        f.apply_tag("2.0.0")
        f.assert_full_semver("2.0.0", c)
        f.checkout("support/1.x")
        f.branch_to("hotfix/1.2.2")
        f.assert_full_semver("1.2.2-beta.1+1", c)
        f.make_a_commit()
        f.make_a_commit()
        f.assert_full_semver("1.2.2-beta.1+3", c)
        f.apply_tag("1.2.3-beta.1")
        f.assert_full_semver("1.2.3-beta.2+0", c)
        f.make_a_commit()
        f.assert_full_semver("1.2.3-beta.2+1", c)
        _finish_into(f, "support/1.x", "hotfix/1.2.2", "1.2.3-PullRequest2.5", with_pr)
        f.assert_full_semver("1.2.3-5", c)
        f.apply_tag("1.2.3")
        f.assert_full_semver("1.2.3", c)
        f.checkout("main")
        f.assert_full_semver("2.0.0", c)
        f.merge_no_ff("support/1.x")
        f.assert_full_semver("2.0.1-6", c)
        f.apply_tag("2.0.1")
        f.assert_full_semver("2.0.1", c)
        f.checkout("support/1.x")
        f.make_a_commit()
        f.assert_full_semver("1.2.4-1", c)
        f.apply_tag("1.2.4")
        f.assert_full_semver("1.2.4", c)
        f.checkout("main")
        f.merge_no_ff("support/1.x")
        f.assert_full_semver("2.0.2-2", c)
        f.apply_tag("2.0.2")
        f.assert_full_semver("2.0.2", c)


@pytest.mark.skip(reason="Mainline variants land in Phase 4")
def test_mainline_variants() -> None:
    pass
